export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      operator_profiles: {
        Row: {
          user_id: string;
          access_id: string | null;
          email: string | null;
          full_name: string | null;
          role: "operator" | "admin";
          status: "active" | "revoked";
          can_view_all: boolean;
          can_edit_all: boolean;
          view_group_keys: string[];
          edit_group_keys: string[];
          view_company_ids: number[];
          edit_company_ids: number[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          access_id?: string | null;
          email?: string | null;
          full_name?: string | null;
          role?: "operator" | "admin";
          status?: "active" | "revoked";
          can_view_all?: boolean;
          can_edit_all?: boolean;
          view_group_keys?: string[];
          edit_group_keys?: string[];
          view_company_ids?: number[];
          edit_company_ids?: number[];
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["operator_profiles"]["Insert"]>;
        Relationships: [];
      };
      operator_access: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          role: "operator" | "admin";
          status: "active" | "revoked";
          can_view_all: boolean;
          can_edit_all: boolean;
          view_group_keys: string[];
          edit_group_keys: string[];
          view_company_ids: number[];
          edit_company_ids: number[];
          created_by: string | null;
          revoked_by: string | null;
          revoked_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          full_name?: string | null;
          role?: "operator" | "admin";
          status?: "active" | "revoked";
          can_view_all?: boolean;
          can_edit_all?: boolean;
          view_group_keys?: string[];
          edit_group_keys?: string[];
          view_company_ids?: number[];
          edit_company_ids?: number[];
          created_by?: string | null;
          revoked_by?: string | null;
          revoked_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["operator_access"]["Insert"]>;
        Relationships: [];
      };
      employee_directory: {
        Row: {
          id: string;
          nexti_person_id: number;
          person_external_id: string;
          enrolment: string;
          enrolment_aliases: string[];
          cpf_digits: string;
          full_name: string;
          phone: string | null;
          phone2: string | null;
          whatsapp_phone: string | null;
          group_key: string;
          company_id: number | null;
          company_name: string;
          company_external_id: string | null;
          company_number: string | null;
          business_unit_id: number | null;
          business_unit_name: string | null;
          workplace_id: number | null;
          workplace_external_id: string | null;
          workplace_name: string | null;
          client_name: string | null;
          career_id: number | null;
          career_external_id: string | null;
          career_name: string | null;
          schedule_id: number | null;
          schedule_external_id: string | null;
          schedule_name: string | null;
          shift_id: number | null;
          shift_external_id: string | null;
          shift_name: string | null;
          rotation_id: number | null;
          rotation_code: number | null;
          person_situation_id: number;
          situation_label: string;
          admission_date: string | null;
          is_active: boolean;
          sync_fingerprint: string;
          created_at: string;
          updated_at: string;
          last_synced_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["employee_directory"]["Row"], "id" | "created_at" | "updated_at"> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["employee_directory"]["Insert"]>;
        Relationships: [];
      };
      workplace_directory: {
        Row: {
          id: string;
          nexti_workplace_id: number;
          workplace_external_id: string;
          name: string;
          client_name: string | null;
          service_name: string | null;
          group_key: string;
          company_id: number | null;
          company_name: string | null;
          company_external_id: string | null;
          company_number: string | null;
          business_unit_id: number | null;
          business_unit_name: string | null;
          is_active: boolean;
          sync_fingerprint: string;
          created_at: string;
          updated_at: string;
          last_synced_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["workplace_directory"]["Row"], "id" | "created_at" | "updated_at"> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["workplace_directory"]["Insert"]>;
        Relationships: [];
      };
      portal_requests: {
        Row: {
          id: string;
          request_type: "swap" | "ft";
          workflow_status: "submitted" | "approved" | "rejected" | "cancelled";
          launch_status: "waiting" | "matched" | "not_found" | "error";
          launch_source: "schedule_transfer" | "replacement" | "manual";
          operational_status: "pending" | "approved" | "rejected" | "cancelled" | "launched" | "launched_manual" | "corrected";
          origin: string;
          group_key: string;
          payroll_reference: string;
          payroll_period_start: string;
          payroll_period_end: string;
          requester_employee_id: string;
          substitute_employee_id: string | null;
          requester_nexti_person_id: number;
          substitute_nexti_person_id: number | null;
          requester_person_external_id: string;
          substitute_person_external_id: string | null;
          requester_name: string;
          requester_enrolment: string;
          substitute_name: string | null;
          substitute_enrolment: string | null;
          company_id: number | null;
          company_name: string;
          career_id: number | null;
          career_name: string;
          schedule_id: number | null;
          schedule_name: string | null;
          shift_id: number | null;
          shift_name: string | null;
          workplace_id: number | null;
          workplace_external_id: string | null;
          workplace_name: string | null;
          request_date: string;
          coverage_date: string | null;
          reason: string;
          validation_summary: Json;
          request_snapshot: Json;
          nexti_payload: Json;
          nexti_match_payload: Json;
          launch_error: string | null;
          approved_at: string | null;
          approved_by: string | null;
          rejected_at: string | null;
          rejected_by: string | null;
          cancelled_at: string | null;
          cancelled_by_employee_id: string | null;
          cancel_reason: string | null;
          launched_at: string | null;
          assigned_operator_user_id: string | null;
          assigned_operator_name: string | null;
          operation_note: string | null;
          manual_authorization_note: string | null;
          manual_created_by: string | null;
          manual_created_at: string | null;
          manual_launched_by: string | null;
          manual_launched_at: string | null;
          ft_reason_id: string | null;
          ft_reason_label: string | null;
          covered_employee_id: string | null;
          covered_nexti_person_id: number | null;
          covered_person_external_id: string | null;
          covered_name: string | null;
          covered_enrolment: string | null;
          selected_shift_directory_id: string | null;
          selected_shift_id: number | null;
          selected_shift_external_id: string | null;
          selected_shift_name: string | null;
          selected_shift_turn: "diurno" | "noturno" | "indefinido" | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          request_type: "swap" | "ft";
          workflow_status?: "submitted" | "approved" | "rejected" | "cancelled";
          launch_status?: "waiting" | "matched" | "not_found" | "error";
          launch_source: "schedule_transfer" | "replacement" | "manual";
          operational_status?: "pending" | "approved" | "rejected" | "cancelled" | "launched" | "launched_manual" | "corrected";
          origin?: string;
          group_key: string;
          payroll_reference: string;
          payroll_period_start: string;
          payroll_period_end: string;
          requester_employee_id: string;
          substitute_employee_id?: string | null;
          requester_nexti_person_id: number;
          substitute_nexti_person_id?: number | null;
          requester_person_external_id: string;
          substitute_person_external_id?: string | null;
          requester_name: string;
          requester_enrolment: string;
          substitute_name?: string | null;
          substitute_enrolment?: string | null;
          company_id?: number | null;
          company_name: string;
          career_id?: number | null;
          career_name: string;
          schedule_id?: number | null;
          schedule_name?: string | null;
          shift_id?: number | null;
          shift_name?: string | null;
          workplace_id?: number | null;
          workplace_external_id?: string | null;
          workplace_name?: string | null;
          request_date: string;
          coverage_date?: string | null;
          reason: string;
          validation_summary?: Json;
          request_snapshot?: Json;
          nexti_payload?: Json;
          nexti_match_payload?: Json;
          launch_error?: string | null;
          approved_at?: string | null;
          approved_by?: string | null;
          rejected_at?: string | null;
          rejected_by?: string | null;
          cancelled_at?: string | null;
          cancelled_by_employee_id?: string | null;
          cancel_reason?: string | null;
          launched_at?: string | null;
          assigned_operator_user_id?: string | null;
          assigned_operator_name?: string | null;
          operation_note?: string | null;
          manual_authorization_note?: string | null;
          manual_created_by?: string | null;
          manual_created_at?: string | null;
          manual_launched_by?: string | null;
          manual_launched_at?: string | null;
          ft_reason_id?: string | null;
          ft_reason_label?: string | null;
          covered_employee_id?: string | null;
          covered_nexti_person_id?: number | null;
          covered_person_external_id?: string | null;
          covered_name?: string | null;
          covered_enrolment?: string | null;
          selected_shift_directory_id?: string | null;
          selected_shift_id?: number | null;
          selected_shift_external_id?: string | null;
          selected_shift_name?: string | null;
          selected_shift_turn?: "diurno" | "noturno" | "indefinido" | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["portal_requests"]["Insert"]>;
        Relationships: [];
      };
      request_events: {
        Row: {
          id: string;
          request_id: string;
          actor_type: "employee" | "operator" | "system";
          actor_id: string | null;
          actor_label: string | null;
          event_type: string;
          payload: Json;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["request_events"]["Row"], "id" | "created_at"> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["request_events"]["Insert"]>;
        Relationships: [];
      };
      operator_assignments: {
        Row: {
          id: string;
          request_id: string;
          operator_user_id: string;
          assigned_by_user_id: string | null;
          operator_name: string | null;
          note: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["operator_assignments"]["Row"], "id" | "created_at"> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["operator_assignments"]["Insert"]>;
        Relationships: [];
      };
      nexti_sync_state: {
        Row: {
          sync_key: string;
          last_cursor_start: string | null;
          last_cursor_finish: string | null;
          last_success_at: string | null;
          last_error: string | null;
          metadata: Json;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["nexti_sync_state"]["Row"], "updated_at"> & {
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["nexti_sync_state"]["Insert"]>;
        Relationships: [];
      };
      nexti_launch_history: {
        Row: {
          id: string;
          request_type: "swap" | "ft";
          nexti_source: "schedule_transfer" | "replacement";
          nexti_record_id: number;
          nexti_record_external_id: string | null;
          group_key: string;
          payroll_reference: string;
          payroll_period_start: string;
          payroll_period_end: string;
          requester_employee_id: string | null;
          requester_nexti_person_id: number | null;
          requester_person_external_id: string | null;
          requester_name: string;
          requester_enrolment: string | null;
          requester_is_active: boolean;
          substitute_nexti_person_id: number | null;
          substitute_person_external_id: string | null;
          substitute_name: string | null;
          substitute_enrolment: string | null;
          company_id: number | null;
          company_name: string | null;
          career_id: number | null;
          career_name: string | null;
          schedule_id: number | null;
          schedule_name: string | null;
          shift_id: number | null;
          shift_external_id: string | null;
          shift_name: string | null;
          workplace_id: number | null;
          workplace_external_id: string | null;
          workplace_name: string | null;
          request_date: string;
          coverage_date: string | null;
          nexti_created_at: string | null;
          nexti_last_update: string | null;
          raw_payload: Json;
          created_at: string;
          updated_at: string;
          last_synced_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["nexti_launch_history"]["Row"], "id" | "created_at" | "updated_at"> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["nexti_launch_history"]["Insert"]>;
        Relationships: [];
      };
      nexti_launch_history_sync_state: {
        Row: {
          sync_key: string;
          last_cursor_start: string | null;
          last_cursor_finish: string | null;
          last_success_at: string | null;
          last_error: string | null;
          metadata: Json;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["nexti_launch_history_sync_state"]["Row"], "updated_at"> & {
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["nexti_launch_history_sync_state"]["Insert"]>;
        Relationships: [];
      };
      whatsapp_notification_rules: {
        Row: {
          id: string;
          scope_type: "global" | "group" | "company" | "workplace" | "employee" | "request_type";
          scope_key: string;
          request_type: "swap" | "ft" | null;
          enabled: boolean;
          note: string | null;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          scope_type: "global" | "group" | "company" | "workplace" | "employee" | "request_type";
          scope_key: string;
          request_type?: "swap" | "ft" | null;
          enabled?: boolean;
          note?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["whatsapp_notification_rules"]["Insert"]>;
        Relationships: [];
      };
      whatsapp_send_events: {
        Row: {
          id: string;
          event_type: string;
          target_type: "portal_request" | "nexti_history";
          target_id: string;
          operator_user_id: string | null;
          operator_email: string | null;
          operator_name: string | null;
          employee_nexti_person_id: number | null;
          employee_name: string | null;
          employee_enrolment: string | null;
          phone_raw: string | null;
          phone_normalized: string | null;
          message: string;
          wa_url: string;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["whatsapp_send_events"]["Row"], "id" | "created_at"> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["whatsapp_send_events"]["Insert"]>;
        Relationships: [];
      };
      career_equivalence_rules: {
        Row: {
          id: string;
          rule_key: string;
          label: string;
          group_key: string | null;
          match_mode: "exact" | "prefix" | "contains";
          match_pattern: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          rule_key: string;
          label: string;
          group_key?: string | null;
          match_mode?: "exact" | "prefix" | "contains";
          match_pattern: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["career_equivalence_rules"]["Insert"]>;
        Relationships: [];
      };
      ft_reasons: {
        Row: {
          id: string;
          label: string;
          requires_covered_employee: boolean;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          label: string;
          requires_covered_employee?: boolean;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["ft_reasons"]["Insert"]>;
        Relationships: [];
      };
      shift_directory: {
        Row: {
          id: string;
          nexti_shift_id: number;
          shift_external_id: string | null;
          name: string;
          turn: "diurno" | "noturno" | "indefinido";
          is_pre_assigned: boolean;
          is_active: boolean;
          sync_fingerprint: string;
          created_at: string;
          updated_at: string;
          last_synced_at: string;
        };
        Insert: {
          id?: string;
          nexti_shift_id: number;
          shift_external_id?: string | null;
          name: string;
          turn?: "diurno" | "noturno" | "indefinido";
          is_pre_assigned?: boolean;
          is_active?: boolean;
          sync_fingerprint?: string;
          created_at?: string;
          updated_at?: string;
          last_synced_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["shift_directory"]["Insert"]>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
